resolver: lts-18.27

packages:
- .

extra-deps:
- git: git@github.com:haskell-effectful/effectful.git
  commit: 9034e8f572d99cd7abdd8ad32aef6bc3ce342e46
  subdirs:
  - effectful-core
  - effectful-th
  - effectful
