resolver: lts-19.7

packages:
- .

extra-deps:
- git: git@github.com:haskell-effectful/effectful.git
  commit: ba4798f1eb540d9b4d13a3463f79ce0633cbb656
  subdirs:
  - effectful-core
  - effectful-th
  - effectful
