resolver: lts-18.24

packages:
- .

extra-deps:
- git: git@github.com:haskell-effectful/effectful.git
  commit: 24ea29a1344e3f821fbce3ea5f7c4e25d4ea1c3d
  subdirs:
  - effectful-core
  - effectful-th
  - effectful
