resolver: lts-19.1

packages:
- .

extra-deps:
- git: git@github.com:haskell-effectful/effectful.git
  commit: 5d7ed78936d2811792c12ef9532caaa1fdeb1db9
  subdirs:
  - effectful-core
  - effectful-th
  - effectful
